name: 'Deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Deploy Themes
        env:
          FUSION_AUTH_API_TOKEN: ${{ secrets.FUSION_AUTH_API_TOKEN }}
          HOST: ${{ secrets.HOST }}
        run: python theme.py push --yes

      - name: Deploy Email Templates
        env:
          FUSION_AUTH_API_TOKEN: ${{ secrets.FUSION_AUTH_API_TOKEN }}
          HOST: ${{ secrets.HOST }}
        run: python emails.py push --yes
